### ISSUE TITLE
Add CodeSandbox demo

### ISSUE THREAD

**Issue by newyork-anthonyng** [hanford/defer-render-hoc#2]
I think a working demo that users can play with on `CodeSandbox` would be extremely helpful.

[This was a simple one I threw together.](https://codesandbox.io/s/yk359090r1). If you think a CdoeSandbox demo is a good idea, I can clean it up with some better documentation and update the README.md.

Let me know and I can create a Pull Request.

**Comment by hanford** [comment]
Love this! 👍  Would absolutely merge
